//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Match_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchDetail
    {
        public int MatchDetailId { get; set; }
        public Nullable<int> MatchId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public string PlayerType { get; set; }
        public string Position { get; set; }
        public string TeamId { get; set; }
    
        public virtual Match Match { get; set; }
    }
}
