//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Match_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public Match()
        {
            this.MatchDetails = new HashSet<MatchDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TeamOneId { get; set; }
        public Nullable<int> TeamTwoId { get; set; }
        public string MatchName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<MatchDetail> MatchDetails { get; set; }
    }
}
